"""empty message

Revision ID: 000003
Revises: 000002
Create Date: 2020-02-13 14:34:51.160922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000003'
down_revision = '000002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('category_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('category_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category')
    # ### end Alembic commands ###
