"""empty message

Revision ID: 000006
Revises: 000005
Create Date: 2020-02-14 09:19:38.217823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000006'
down_revision = '000005'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', sa.String(length=32), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###
