"""empty message

Revision ID: 000007
Revises: 000006
Create Date: 2020-02-14 11:48:50.266485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '000007'
down_revision = '000006'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'salt')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('salt', mysql.VARCHAR(length=32), nullable=False))
    # ### end Alembic commands ###
