"""empty message

Revision ID: 000008
Revises: 000007
Create Date: 2020-02-17 15:34:01.293801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000008'
down_revision = '000007'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('level_questions',
    sa.Column('level_question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['level.level_id'], name='fk_level_question'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='fk_question_level'),
    sa.PrimaryKeyConstraint('level_question_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('level_questions')
    # ### end Alembic commands ###
