"""empty message

Revision ID: 000005
Revises: 000004
Create Date: 2020-02-13 14:57:12.176684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000005'
down_revision = '000004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer',
    sa.Column('answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('answer_id')
    )
    op.create_table('question_type',
    sa.Column('type_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('type_id')
    )
    op.create_table('question',
    sa.Column('question_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('type_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['type_id'], ['question_type.type_id'], name='fk_question_type'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_table('question_answers',
    sa.Column('question_answer_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('answer_id', sa.Integer(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answer.answer_id'], name='fk_answer_question'),
    sa.ForeignKeyConstraint(['question_id'], ['question.question_id'], name='fk_question_answer'),
    sa.PrimaryKeyConstraint('question_answer_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('question_answers')
    op.drop_table('question')
    op.drop_table('question_type')
    op.drop_table('answer')
    # ### end Alembic commands ###
